### ISSUE TITLE
Visualization & Reports Expansion

### ISSUE THREAD

**Issue by sgiavasis** [preprocessed-connectomes-project/quality-assessment-protocol#95]

**Comment by carolFrohlich** [comment]
- [ ] create html template 
- [ ]  cp template to subject output when subject finished running
- [ ] substitute names and patjs on html template
- [ ] create plot Mean fd + DVARS + global signal
- [ ]  create gay plot
- [ ]  create mean epi mosaic
- [ ]  create signal fluctuation sensitivity mosaic
